import mongoose from 'mongoose';

const projectSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  title: { type: String, required: true },
  description: { type: String },
  deadline: { type: Date },
  tags: [String],
  priority: { type: String, enum: ['High', 'Medium', 'Low'], default: 'Medium' },
  // ADDED: This field will store the tasks generated by the AI
  tasks: [{
    text: { type: String, required: true },
    completed: { type: Boolean, default: false }
  }]
}, { timestamps: true });

export default mongoose.model('Project', projectSchema);